building_damage/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

from core import views
from core import urls
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.upload_images, name='upload_images'),
    path('list_results', views.list_results, name='list_results'),
    path('result/<int:pk>/', views.show_result, name='result'),
    path('edit/<int:pk>/', views.edit_result, name='edit'),
    path('delete/<int:pk>/', views.delete_result, name='delete'),
    ]

core/models.py
from django.db import models

class ImagePair(models.Model):
    title = models.CharField(max_length=50, blank=True)
    pre_image = models.ImageField(upload_to='pre_images/')
    post_image = models.ImageField(upload_to='post_images/')
    output_segment = models.ImageField(upload_to='segment_masks/', blank=True)
    output_damage = models.ImageField(upload_to='damage_masks/', blank=True)
    damage_percentage = models.FloatField(blank=True,null=True)

core/forms.py
from django import forms
from .models import ImagePair
from PIL import Image
from django.core.exceptions import ValidationError


class ImagePairForm(forms.ModelForm):
    
    class Meta:
        model = ImagePair
        fields = ['title', 'pre_image', 'post_image']

    def clean(self):
        cleaned_data = super().clean()
        pre_image = cleaned_data.get('pre_image')
        post_image = cleaned_data.get('post_image')

        if pre_image and post_image:
            pre_image_size = Image.open(pre_image).size
            post_image_size = Image.open(post_image).size

            if pre_image_size != post_image_size:
                raise forms.ValidationError("Both images must be equal in size.")

            if pre_image_size[0] < 256 or pre_image_size[1] < 256:
                raise forms.ValidationError("Image dimensions must be larger than 256x256.")

        return cleaned_data
    

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ImagePairForm
from .models import ImagePair
from .utils import process_images_with_model  
from PIL import Image

def upload_images(request):
    if request.method == 'POST':

        form = ImagePairForm(request.POST, request.FILES)

        if form.is_valid():

            image_pair = form.save()
            process_images_with_model(image_pair)

            return redirect('result', pk=image_pair.pk)
        
    else:
        form = ImagePairForm()
    return render(request, 'core/upload_images.html', {'form': form})


def list_results(request):
    recent_results = ImagePair.objects.all()
    return render(request, 'core/list_results.html', {'recent_results':recent_results})

                                                       
def show_result(request, pk):
    image_pair = ImagePair.objects.get(pk=pk)
    return render(request, 'core/result.html', {'image_pair': image_pair})

def edit_result(request, pk):

    def edit_image_pair(request, pk):
        recent_results = ImagePair.objects.all()

    image_pair = get_object_or_404(ImagePair, pk=pk)

    if request.method == 'POST':
        form = ImagePairForm(request.POST, request.FILES, instance=image_pair)

        if form.is_valid():
            pre_image = request.FILES['pre_image']
            post_image = request.FILES['post_image']
            validate_uploaded_images(pre_image, post_image, request)
            image_pair = form.save()
            process_images_with_model(image_pair)
            return redirect('result', pk=image_pair.pk)
    else:
        image_pair = ImagePair.objects.get(pk=pk)
        return render(request, 'core/edit.html', {'image_pair': image_pair})

def delete_result(request, pk):
    image_pair = ImagePair.objects.get(pk=pk)
    if request.method == 'POST':
        image_pair.delete()
    return redirect('list_results')


def validate_uploaded_images(pre_image, post_image, request, form):
    def get_image_dimensions(image):
        with Image.open(image) as img:
            return img.size

    min_size = 256

    if get_image_dimensions(pre_image) != get_image_dimensions(post_image):
        return render(request, 'core/upload_images.html', {'form': form})
    if any(dim <= min_size for dim in get_image_dimensions(pre_image)):
        return render(request, 'core/upload_images.html', {'form': form})
    if any(dim <= min_size for dim in get_image_dimensions(post_image)):
        return render(request, 'core/upload_images.html', {'form': form})

core/templates/core/edit.html
{% extends "core/main.html" %}


{% block content %}
<h2 class="text-2xl font-bold text-white">
    Edit
</h2>

<div>
    <form method="post" enctype="multipart/form-data" action="{% url 'upload_images' %}">
        {% csrf_token %}


        <div class="flex flex-col space-y-4 my-8">
            <div>
                <label for="id_title"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Title:</label>
                <input type="text" name="title" id="id_title" value="{{ image_pair.title }}"
                    class="px-4 block w-full h-10 text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 rounded-2xl file:rounded-xl file:border-0 file:text-sm file:font-semibold bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 ">
                {{ form.title.errors }}
            </div>

            <div class="grid grid-cols-2 gap-4">
                <div>
                    <label for="id_pre_image" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Pre
                        Image:
                    </label>
                    <input type="file" name="pre_image" id="id_pre_image" value="{{image_pair.pre_image.url}}"
                        class="block w-full h-10 file:h-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 rounded-2xl file:border-0 file:text-sm file:font-semibold bg-white file:text-blue-700 hover:file:bg-blue-100">
                    {{ form.pre_image.errors }}
                    <img src="{{image_pair.pre_image.url}}" alt="">
                </div>

                <div>
                    <label for="id_post_image" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Post
                        Image:
                    </label>
                    <input type="file" name="post_image" id="id_post_image" value="{{image_pair.post_image.url}}"
                        class="block w-full h-10 file:h-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 rounded-2xl file:border-0 file:text-sm file:font-semibold bg-white file:text-blue-700 hover:file:bg-blue-100">
                    {{ form.post_image.errors }}
                    <img src="{{image_pair.post_image.url}}" alt="">

                </div>
            </div>
        </div>

        <div class="flex justify-center my-4">
            <div>
                <button
                    class="mx-auto text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    Process
                </button>
            </div>
        </div>

    </form>
</div>

{% endblock %}

core/templates/core/list_results.html
{% extends "core/main.html" %}


{% block content %}
<h2 class="text-2xl font-bold text-white">
    Bina Hasar Tespiti Sonuclari
</h2>

<div class="text-white mt-12">
    <table class="w-full table-auto border border-slate-500 ">
        <thead>
            <tr>
                <th class="border border-slate-700 p-3 bg-blue-800">
                    <div class="flex">
                        ID
                    </div>
                </th>
                <th class="border border-slate-700 p-3 bg-blue-800">
                    <div class="flex">
                        Title
                    </div>
                </th>
                <th class="border border-slate-700 p-3 bg-blue-800">
                    <div class="flex">
                        Show
                    </div>
                </th>
                <th class="border border-slate-700 p-3 bg-blue-800">
                    <div class="flex">
                        Edit
                    </div>
                </th>
                <th class="border border-slate-700 p-3 bg-blue-800">
                    <div class="flex">
                        Delete
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for result_item in recent_results %}
            <tr>
                <td class="border border-slate-700 p-3">
                    {{result_item.id}}
                </td>
                <td class="border border-slate-700 p-3">
                    {{result_item.title}}
                </td>
                <td class="border border-slate-700 p-3">
                    <a href="{% url 'result' result_item.id %}">
                        Show
                    </a>
                </td>
                <td class="border border-slate-700 p-3">
                    <a href="{% url 'edit' result_item.id %}">
                        Edit
                    </a>
                </td>
                <td class="border border-slate-700 p-3">
                    <form action="{% url 'delete' result_item.id %}" method="post">
                        {% csrf_token %}
                        <button >Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>



{% endblock %}

core/templates/core/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <!-- <script src='main.js'></script> -->
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="bg-gray-900 ">
    {% include "core/navbar.html" %}

    <section class='flex flex-col items-center justify-center overflow-hidden bg-sky-200 dark:bg-gray-900 pt-16 pb-20 px-6 lg:px-8'>
        <div class='mx-auto max-w-6xl container '>

            {% block content %}
            {% endblock %}

        </div>
    </section>
</body>
</html>

core/templates/core/navbar.html
<div class="bg-blue-800 h-20 text-2xl font-bold text-white flex justify-center ">
    <div class="mx-auto max-w-6xl container">
        <div class="flex  space-x-8  h-full">
            <div class="flex items-center">
                <a href="{% url 'upload_images' %}">
                    upload_images
                </a>
            </div>
            <div class="flex items-center ">
                <a href="{% url 'list_results' %}">
                    list_results
                </a>
            </div>
    </div>
    </div>
</div>

core/templates/core/result.html
{% extends "core/main.html" %}

   
{% block content %}

<h2 class="text-2xl font-bold text-white">
    Result Page
</h2>

<div class="grid grid-cols-1 text-white">

    <h3 class="text-2xl text-white my-8">Pre</h3>
    <div class="grid grid-cols-2 gap-12 justify-items-center">
        <img src="{{ image_pair.pre_image.url }}" alt="Input Image 1" class="" style="height: 480px">
        <img src="{{ image_pair.output_segment.url }}" alt="Output Image 1" class="" style="height: 480px">

    </div>

    <h3 class="text-2xl text-white my-8">Post</h3>
    <div class="text-xl mb-4">Damage percentage: {{ image_pair.damage_percentage }}%</div>
    <div class="grid grid-cols-2 gap-12 justify-items-center">
        <img src="{{ image_pair.post_image.url }}" alt="Input Image 2" class="" style="height: 480px">
        <img src="{{ image_pair.output_damage.url }}" alt="Output Image 2" class="" style="height: 480px">
    </div>
</div>

{% endblock %}

core/templates/core/upload_images.html
{% extends "core/main.html" %}


{% block content %}
<h2 class="text-2xl font-bold text-white mb-4 ">
    Bina Hasar Tespiti
</h2>

<div class="text-white bg-gray-500/50 px-8 py-2 rounded-2xl ">
    <form method="post" enctype="multipart/form-data" action="{% url 'upload_images' %}">
        {% csrf_token %}


        <div class="flex flex-col space-y-4 my-8">
            <div>
                <label for="id_title"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Başlık:</label>
                <input type="text" name="title" id="id_title" value=""
                    class="px-4 block w-full h-10 text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 rounded-2xl file:rounded-xl file:border-0 file:text-sm file:font-semibold bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 ">
                {{ form.title.errors }}
            </div>

            <div class="grid grid-cols-2 gap-4">

                <div>
                    <label for="id_pre_image" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Felaketten önceki görüntü:</label>
                    <input type="file" name="pre_image" id="id_pre_image"
                        onchange="previewImage(event, 'id_pre_image', 'preview_pre', 'deleteButton_pre')"
                        class="block w-full h-10 file:h-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 rounded-2xl file:border-0 file:text-sm file:font-semibold bg-white file:text-blue-700 hover:file:bg-blue-100">
                    {{ form.pre_image.errors }}
                    <button onclick="deleteImage('id_pre_image', 'preview_pre', 'deleteButton_pre')" class="hidden"
                        id="deleteButton_pre" type="button">Delete</button>

                </div>

                <div>
                    <label for="id_post_image" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Felaketten sonraki görüntü:</label>
                    <input type="file" name="post_image" id="id_post_image"
                        onchange="previewImage(event, 'id_post_image', 'preview_post', 'deleteButton_post')"
                        class="block w-full h-10 file:h-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 rounded-2xl file:border-0 file:text-sm file:font-semibold bg-white file:text-blue-700 hover:file:bg-blue-100">
                    <button onclick="deleteImage('id_post_image', 'preview_post', 'deleteButton_post')" class="hidden"
                        id="deleteButton_post" type="button">Delete</button>

                    {{ form.post_image.errors }}
                </div>

                <div>

                    <img id="preview_pre" src="#" alt="Preview" class="w-full p-2 rounded-2xl hidden">

                </div>
                <div>
                    <img id="preview_post" src="#" alt="Preview" class="w-full p-2 rounded-2xl hidden">

                </div>
            </div>
        </div>

        <div>
            <!-- {% if form.errors %}
            <div class="error-message">
                <p>{{ form.errors }}</p>
            </div>
            {% endif %} -->
            {% if form.non_field_errors %}
            <div class="error-message">
                {% for error in form.non_field_errors %}
                <p>{{ error }}</p>
                {% endfor %}
            </div>
            {% endif %}

        </div>

        <div class="flex justify-center my-4">
            <div>
                <button
                    class="mx-auto text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    Process
                </button>
            </div>
        </div>

    </form>
</div>


<script>
    function previewImage(event, inputId, previewId, deleteButtonId) {
        var input = document.getElementById(inputId);
        var preview = document.getElementById(previewId);
        var deleteButton = document.getElementById(deleteButtonId);

        var reader = new FileReader();

        reader.onload = function () {
            preview.src = reader.result;
            preview.classList.remove('hidden');
            deleteButton.classList.remove('hidden');
        };

        reader.readAsDataURL(input.files[0]);
    }

    function deleteImage(inputId, previewId, deleteButtonId) {
        var input = document.getElementById(inputId);
        var preview = document.getElementById(previewId);
        var deleteButton = document.getElementById(deleteButtonId);

        input.value = '';

        preview.src = '';

        preview.classList.add('hidden');
        deleteButton.classList.add('hidden');
    }

</script>

{% endblock %}